# Site settings
title: Notpad. 
email: almendar@gmail.com
description: Tomasz Kogut personal programming notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://almendar.github.io" # the base hostname & protocol for your site
twitter_username: almendar
github_username:  almendar

# Build settings
markdown: kramdown
highlighter: pygments
